# Exported from Render on 2024-06-06T21:40:02Z
services:
- type: web
  name: mysite
  runtime: ruby
  repo: https://github.com/stanley021/myapp
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
